server:
  port: 8080

spring:
  application:
    name: library

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: Library@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate     # Hibernate chỉ kiểm tra entity khớp schema, không tự sửa DB
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      timeout: 2s
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
app:
  jwt:
    secret: "3pHoX9WySmdbsP4vnkuM4o+Lrd/n5ejYcDYOBufMGXEVLABgSWU/TFAwYBanP6VywMIb6B/Px4KIZ/4xXmflyg=="
    access-expiration-ms: 1800000      # 30 phút
    refresh-expiration-ms: 604800000   # 7 ngày
  setting-key:
    fine-overdue-per-day: "FINE_OVERDUE_PER_DAY"
    fine-lost-rate: "FINE_LOST_RATE"
    fine-damaged-light-rate: "FINE_DAMAGED_LIGHT_RATE"
    fine-damaged-heavy-repairable-rate: "FINE_DAMAGED_HEAVY_REPAIRABLE_RATE"
    fine-damaged-heavy-irreparable-rate: "FINE_DAMAGED_HEAVY_IRREPARABLE_RATE"
    max-borrow-days: "MAX_BORROW_DAYS"
    max-book-borrow: "MAX_BOOKS_BORROW"
    max-fine-before-block: "MAX_FINE_BEFORE_BLOCK"
    due-reminder-days: "DUE_REMINDER_DAYS"
    member-payment-month: "MEMBER_PAYMENT_MONTH"
    card-maker-fee: "CARD_MAKER_FEE"
